name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
        java: [ '16', '17', '18', '19', '20' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
      - name: Build native programs (Linux only)
        if: runner.os == 'Linux'
        run: make -C native
      - name: Build and test with Maven
        run: mvn package
      - name: Test with latest MOEA Framework JAR
        run: |
          VERSION=$(curl https://api.github.com/repos/MOEAFramework/MOEAFramework/releases/latest | jq '.tag_name' | grep -oEi '[0-9]+\.[0-9]+(\.[0-9]+)?')
          wget https://github.com/MOEAFramework/MOEAFramework/releases/download/v${VERSION}/MOEAFramework-${VERSION}.tar.gz
          tar -xzf MOEAFramework-${VERSION}.tar.gz

          MOEAFRAMEWORK_ROOT=$(realpath -s MOEAFramework-${VERSION})
          ln -s $(realpath -s native/) ${MOEAFRAMEWORK_ROOT}/native
          cp target/real-world-benchmarks-[0-9].[0-9].[0-9].jar ${MOEAFRAMEWORK_ROOT}/lib

          cd ${MOEAFRAMEWORK_ROOT}
          java -cp "lib/*" org.moeaframework.analysis.tools.Solve -a NSGAII -b GAA -n 10000 -f GAA.result
