name: Validate and stage release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version to publish
        required: true
      publish-github:
        description: 'Create draft GitHub release'
        default: true
        type: boolean
      publish-maven:
        description: 'Create Maven release'
        default: true
        type: boolean
      trigger-tests:
        description: 'Trigger integration tests'
        default: true
        type: boolean
      skip-validation:
        description: 'Skip version validations'
        default: false
        type: boolean

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Windows native files
        run: make -C native
      - uses: actions/upload-artifact@v4
        with:
          name: native-windows
          path: native/
  stage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup release
        uses: MOEAFramework/.github/actions/setup-build@main
        with:
          java-version: 19
          setup-git: true
          email: ${{ secrets.EMAIL }}
          username: ${{ secrets.USERNAME }}
          github-token: ${{ secrets.PAT }}
          gpg-signing-key: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Get project info
        uses: MOEAFramework/.github/actions/get-project-info@main
        with:
          expected-version: ${{ inputs.version }}
          skip-validation: ${{ inputs.skip-validation }}
      - name: Build and stage Maven artifacts
        if: ${{ inputs.publish-maven }}
        uses: MOEAFramework/.github/actions/publish-maven@main
        with:
          skip-tests: true
          ossrh-username: ${{ secrets.OSSRH_USERNAME }}
          ossrh-password: ${{ secrets.OSSRH_TOKEN }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Remove native/ folder 
        run: rm -rf native/
      - name: Download Windows native files
        uses: actions/download-artifact@v4
        with:
          name: native-windows
          path: native/
      - name: Zip Windows native files
        run: zip -r native-windows.zip native
      - name: Stage GitHub release
        if: ${{ inputs.publish-github }}
        uses: MOEAFramework/.github/actions/publish-github@main
        with:
          extra-files: native-windows.zip
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger integration tests
        uses: MOEAFramework/.github/actions/integration-test@main
        with:
          github-token: ${{ secrets.PAT }}
          
